name: Node CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'


jobs:
  test-ubuntu:
    uses: ./.github/workflows/test.yml
    with:
      os: ubuntu-latest
  test-macos:
    uses: ./.github/workflows/test.yml
    with:
      os: macos-latest
  test-windows:
    uses: ./.github/workflows/test.yml
    with:
      os: windows-latest