name: Node CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'


jobs:
  test-ubuntu:
    uses: ./.github/workflows/test.yml
    needs: prepare-yarn-cache-ubuntu
    with:
      os: ubuntu-latest
  test-macos:
    uses: ./.github/workflows/test.yml
    needs: prepare-yarn-cache-macos
    with:
      os: macos-latest
  test-windows:
    uses: ./.github/workflows/test.yml
    needs: prepare-yarn-cache-windows
    with:
      os: windows-latest